apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtt-service
  namespace: mosquitto-broker
  labels:
    app: mosquitto
spec:
  type: ExternalName
  externalName: mqtt.svc.cluster.local
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      name: mqtt-tcp
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: mqtt-ws
  type: LoadBalancer
