apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mqtt.vpineda.me
  name: mosquitto-mqtt-service
  namespace: mosquitto-broker
  labels:
    app: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      name: mqtt-tcp
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: mqtt-ws
  type: LoadBalancer
