---
apiVersion: v1
kind: Service
metadata:
  name: esphome
  namespace: esphome
  labels:
    app: esphome
spec:
  selector:
    app: esphome
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6052
  type: ClusterIP
