---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esphome-dashboard
  labels:
    app: esphome
spec:
  serviceName: "esphome"
  replicas: 1
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      containers:
      - name: esphome
        image: esphome/esphome:latest # Use the official ESPHome Docker image
        ports:
        - containerPort: 6052 # Default ESPHome dashboard port
        volumeMounts:
        - name: esphome-config
          mountPath: /config
        env:
        - name: ESPHOME_DASHBOARD_USE_PING
          value: "true"
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: esphome-credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: esphome-credentials
              key: password
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: esphome-config
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 200Mi
      storageClassName: longhorn-rc2